### ISSUE TITLE
garbage collector found invalid heap pointer: Go 1.4

### ISSUE THREAD

**Issue by HawaiianSpork** [libgit2/git2go#163] opened 2015-01-01 16:50 UTC
After upgrading from go1.3 to go1.4, I'd get a runtime crash most of the time.  It crashes for various reasons (nil tree walker callback, invalid heap pointer...). Here is a scaled down version of the code that demonstrates the problem (runtime crashes most of the time).  Run this code with an argument pointing at a git repository like git2go.

```go
package main

import (
	"fmt"
	"github.com/libgit2/git2go"
	"os"
	"strings"
)

type MyRepo struct {
	*git.Repository
}

func (repository *MyRepo) foo(path string, treeEntry *git.TreeEntry) int {
	if git.ObjectBlob != treeEntry.Type {
		return 0 // continue
	}

	if !strings.HasSuffix(treeEntry.Name, ".go") {
		return 0 // continue
	}

	blob, err := repository.Repository.LookupBlob(treeEntry.Id)
	defer blob.Free()
	if err != nil {
		panic(err)
	}

	if blob.Size() > 10000 {
		return 0 // continue
	}

	contents := blob.Contents()
	if contents == nil {
		panic("nil contents")
	}
	fmt.Printf("%q", path, treeEntry.Name, string(contents))
	fmt.Println()

	return 0 // continue
}

func main() {
	filename := os.Args[1]

	repository, err := git.OpenRepository(filename)
	if err != nil {
		panic(err)
	}
	defer repository.Free()

	myRepo := MyRepo{repository}

	revWalk, err := repository.Walk()
	if err != nil {
		panic(err)
	}
	defer revWalk.Free()

	// Start out at the head
	err = revWalk.PushHead()
	if err != nil {
		panic(err)
	}

	err = revWalk.Iterate(func(commit *git.Commit) bool {
		defer commit.Free()

		tree, err := commit.Tree()
		if err != nil {
			panic(err)
		}
		defer tree.Free()

		err = tree.Walk(myRepo.foo)
		if err != nil {
			panic(err)
		}

		return true
	})

	if err != nil {
		panic(err)
	}
}
```

Some errors that come from the above code:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40f4299]

goroutine 1 [running]:
github.com/libgit2/git2go.CallbackGitTreeWalk(0x438a520, 0x51008e0, 0xc208071e40, 0x0)
	/Users/maleticm/.gvm/pkgsets/go1.4/jack/src/github.com/libgit2/git2go/tree.go:99 +0x79
github.com/libgit2/git2go._Cfunc__go_git_treewalk(0x5100850, 0x0, 0xc208069e40, 0x0)
	/Users/maleticm/.gvm/pkgsets/go1.4/jack/src/github.com/libgit2/git2go/:402 +0x43
github.com/libgit2/git2go.Tree.Walk(0x5100850, 0xc20802c018, 0x5100850, 0xc208069e80, 0x0, 0x0)
```

```
runtime: garbage collector found invalid heap pointer *(0xc208069cd0+0x10)=0xc208083e40 span=0xc20807e000-0xc208083800-0xc208084000 state=0
fatal error: invalid heap pointer

runtime stack:
runtime.throw(0x437df83)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/panic.go:491 +0xad fp=0x7fff5fbfea18 sp=0x7fff5fbfe9e8
scanblock(0xc208069cd0, 0x20, 0x42c12e4)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/mgc0.c:378 +0x551 fp=0x7fff5fbfeb58 sp=0x7fff5fbfea18
scanframe(0x7fff5fbfec60, 0x0, 0x1)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/mgc0.c:740 +0x1c2 fp=0x7fff5fbfebc8 sp=0x7fff5fbfeb58
```

```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x40f4299]

goroutine 1 [running, locked to thread]:
runtime.gothrow(0x426ec90, 0x5)
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/panic.go:503 +0x8e fp=0xc208069c40 sp=0xc208069c28
runtime.sigpanic()
	/Users/maleticm/.gvm/gos/go1.4/src/runtime/sigpanic_unix.go:29 +0x261 fp=0xc208069c90 sp=0xc208069c40
github.com/libgit2/git2go.CallbackGitTreeWalk(0x438a520, 0x5009680, 0xc208073e40, 0x0)
```

**Comment by carlosmn** [comment] 2015-01-04 16:35
The newer releases of Go (at least that's where I've noticed it) can make the GC free memory from a variable in the middle of a function if the variable isn't in use in the Go code anymore. It's possible that there are some missing defensive copies.

**Comment by kron4eg** [comment] 2015-03-20 13:25
I'm getting same panic, EVEN WITH empty callback, without any prints or anything else. Like this:

	WalkCallback := func(dirPath string, ent *git.TreeEntry) int {
		return 0
	}

	rootTree.Walk(WalkCallback)

**Comment by kron4eg** [comment] 2015-03-21 14:55
@carlosmn 
>It looks like there's a timing aspect to this. 

No it's not timing, it's actual problem with git2go code. In 1.4 invalid (contains int for example) go pointers will cause panic during GC. What we are doing here is instructing Go to treat pointer from C (with int) as it was Go's pointer (unsafe.Pointer) which is wrong. We was able get away with this in 1.3 series, but 1.4 is actually have this fixed. This is by design. If we want to operate foreign pointers uintptr should be used.

**Comment by b35li** [comment] 2015-04-10 08:54
@kron4eg 

I got the same issue like your comments. my go version is "go version go1.4.1 linux/amd64"
How shall I fix this? 

Thanks in advance, it is urgent!!!!

**Comment by kron4eg** [comment] 2015-04-10 08:55
@b35li use go 1.3.3, it's OK there.

**Comment by b35li** [comment] 2015-04-10 09:00
Is there any other way, this module is one part of big project, it is hard to say switch the go version directly for me.

I am confused if the problem is with git2go, why don't we fix in git2go, while we downgrad the go version to suit it?

**Comment by kron4eg** [comment] 2015-04-10 09:02
I think the problem is how git2go handle C pointers. Maybe I'm wrong, but I don't have time to fix it myself :) So I just downgraded.

**Comment by b35li** [comment] 2015-04-10 09:08
@kron4eg Got it. thanks very  much. I will downgrade it and have a try.

@carlosmn Any comments?

**Comment by carlosmn** [comment] 2015-04-10 09:22
@kron4eg if we are using ints as pointers, that's definitely a bug, but I don't know which code you're saying that is doing this.

**Comment by kron4eg** [comment] 2015-04-10 09:35
@carlosmn I can't say exactly (in other case I'd send PR with fix), but looks like int pointer returned from libgit2 itself at some point. And Go1.4 runtime see it and crash.

**Comment by b35li** [comment] 2015-04-10 10:32
@kron4eg Exactly, I have no idea what root cause it is , however, when I downgrade to 1.3.3 it indeed works. wonderful.

@carlosmn if you need any feedback from me, just @ me. Thanks.

**Comment by shinningstar** [comment] 2015-04-18 15:02
I am using 1.4.2 for Tree.Walk testing and it always runtime panic for "nil pointer reference" error.
After printing some log, it shows the callback function pointer(as the payload of git_tree_walk) becomes invalid after a while. It seems that the memory of use provided callback function is recycled by GC.
```go
func CallbackGitTreeWalk(_root *C.char, _entry *C.git_tree_entry, ptr unsafe.Pointer) C.int {
    root := C.GoString(_root)
    entry := _entry
    callback := *(*TreeWalkCallback)(ptr)
    fmt.Println("callback func %v", callback)
    return C.int(callback(root, newTreeEntry(entry)))
}
```
```
callback func 0x488c30
ext/pkg/linux_amd64/golang.org/x/tools/refactor/importgraph.a
callback func 0x488c30
ext/pkg/linux_amd64/golang.org/x/tools/refactor/lexical.a
callback func 0x488c30
ext/pkg/linux_amd64/golang.org/x/tools/refactor/rename.a
callback func <nil>
--- FAIL: TestWalk (5.86s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5251d5]
```

**Comment by shinningstar** [comment] 2015-04-19 22:06
I think the problem is that GC has freed the pointer of callback since it doesn't known that it is referenced by C code. So to prevent GC on the pointer of callback, I've add it into a map and delete it after C._go_git_treewalk call finished. The changed code on tree.go is here:
```go
func (t Tree) Walk(callback TreeWalkCallback) error {
    runtime.LockOSThread()
    defer runtime.UnlockOSThread()
    cbmap := make(map[unsafe.Pointer]interface{}, 1)
    ptr := unsafe.Pointer(&callback)
    cbmap[ptr] = callback
    defer func() { delete(cbmap, ptr) }() 
    err := C._go_git_treewalk(
        t.cast_ptr,
        C.GIT_TREEWALK_PRE,
        ptr,
    )   

    if err < 0 {
        return MakeGitError(err)
    }   

    return nil 
}
```
@carlosmn Do you have any comments on this?
@kron4eg Could you help to test this code on your situation?

**Comment by shinningstar** [comment] 2015-04-19 22:10
By the way, to reproduce the runtime panic on tree_walk, you should walk a larger git repository to make GC happened during walking. Maybe to reduce the percentage of GC by debug.SetGCPercent() is another way.

**Comment by pks-t** [comment] 2015-04-20 09:22
It's easy to reproduce the error when walking a rather big tree when starting off the GC via a goroutine. The following example crashes reliably for me on the Linux kernel repository:

```go
package main

import (
	"fmt"
	git "github.com/libgit2/git2go"
	"os"
	"runtime"
	"time"
)

func main() {
	path := os.Args[1]

	repo, _ := git.OpenRepository(path)
	ref, _ := repo.Head()
	commit, _ := repo.LookupCommit(ref.Target())
	tree, _ := commit.Tree()

	go func() {
		time.Sleep(100 * time.Millisecond)
		runtime.GC()
	}()

	if err := tree.Walk(func(dir string, entry *git.TreeEntry) int {
		fmt.Println(entry.Name)
		return 0
	}); err != nil {
		panic(err)
	}
}
```

**Comment by pks-t** [comment] 2015-04-20 10:01
And yes, the error does not occur anymore after the workaround by @shinningstar is applied. Unfortunately it seems as if we don't have any method to do what we want to do that is completly reliable, as the GC of Go is allowed to copy stacks around, thus causing pointers to become invalid. So if we hand over a Go pointer to a C function and the GC kicks in, causing pointers to become invalid, we're screwed up. As of Go 1.4 handing over Go pointers is not supported (see golang/go#8310).

**Comment by carlosmn** [comment] 2015-04-21 10:21
If the runtime is going to arbitrarily make all of our pointers invalid, we'll have to write an indirection layer, as we keep our pointers long-term.

Whether this is due to the stack moving or overeager GC, we will need a more comprehensive method for converting pointers between libgit2 and the Go code.

**Comment by carlosmn** [comment] 2015-04-21 11:56
I'm currently unable to trigger this error, even when running against the linux repo. I have however created a branch `cmn/pointer-indirection` which should work around both an eager GC and the stack moving issue for this particular code. The rest of the callbacks should also get this treatment.

**Comment by shinningstar** [comment] 2015-04-22 15:58
@carlosmn You could see [issue#10303](https://github.com/golang/go/issues/10303) in golang, maybe it could help.

**Comment by pks-t** [comment] 2015-04-23 08:09
@carlosmn: I've modified the code to use your pointer indirection branch (see [pks-t/git2go/pointer-indirection](https://github.com/pks-t/git2go/tree/pointer-indirection). Seems to work after fixing a bug in the NewHandleList function, at least my code snippet posted above does not error out anymore.

If this is the way we want to go I'll also convert other functions that use Go callbacks in C code.

**Comment by shinningstar** [comment] 2015-04-24 03:13
@pks-t @carlosmn How about using the empty(NOP) function to escape callback to heap, just like go runtime team using? It seems that golang team will using this method in Go1.5 to escape Go world pointer when passing to C world.
```go
//go:noescape
func use(unsafe.Pointer) {}

func (t Tree) Walk(callback TreeWalkCallback) error {
    runtime.LockOSThread()
    defer runtime.UnlockOSThread()

    err := C._go_git_treewalk(
        t.cast_ptr,
        C.GIT_TREEWALK_PRE,
        unsafe.Pointer(&callback),
    )   
    use(unsafe.Pointer(&callback))

    if err < 0 {
        return MakeGitError(err)
    }

    return nil 
}
```

**Comment by pks-t** [comment] 2015-04-24 05:52
Well, for my part I wouldn't really want to rely on workarounds that are not officially documented. For now it is explicitly stated that no Go pointers should be passed into the C world, so I'd like to adhere to that and use the pointer indirection branch of @carlosmn insetad.

**Comment by shinningstar** [comment] 2015-04-24 06:40
@pks-t OK, the pointer indirection is fine. I could patch my project locally and wish it merged into main branch soon.

**Comment by pks-t** [comment] 2015-04-24 09:10
@shinningstar I've already converted most of the code to use pointer indirection, see #196.

**Closed** 2015-05-30 20:23 UTC
