### ISSUE TITLE
Fetch on an invalid remote with default options results in fatal error (SIGABRT)

### ISSUE THREAD

**Issue by clns** [libgit2/git2go#305] opened 2016-04-26 13:02 UTC
When fetching an invalid remote over HTTP(s) (one that returns 4xx status code) the code panics with `fatal error: unexpected signal during runtime execution`. The code to reproduce is simple:

``` go
remote, _ := repo.Remotes.Create("origin", "https://github.com/libgit2/NonExistingRepo")
remote.Fetch([]string{}, &FetchOptions{}, "")
```

The actual error is: (you can see the [complete output here](https://travis-ci.org/clns/git2go/builds/125818660#L422))

```
Assertion failed: (t->cred), function on_headers_complete, file /Users/calin/go/src/github.com/clns/git2go/vendor/libgit2/src/transports/http.c, line 377.
SIGABRT: abort
PC=0x7fff8b0610ae m=0
signal arrived during cgo execution
```

So the assertion that causes this is [libgit2: transports/http.c#L377](https://github.com/libgit2/libgit2/blob/0d72f67f28d52b3d7fb2760484fb51c014273bb2/src/transports/http.c#L377). If you [supply a `CredentialsCallback` to the `FetchOptions`](https://github.com/libgit2/git2go/compare/next...clns:next#diff-a19a72927f61bd2e1da14a387c727379R199) then it doesn't break anymore.

I have [some tests here](https://github.com/libgit2/git2go/compare/next...clns:next#diff-a19a72927f61bd2e1da14a387c727379) that demonstrate the failure and you can see the [build on Travis](https://travis-ci.org/clns/git2go/builds/125818660).

This might be a libgit2 issue but it was easier for me to replicate it here. Note that the code uses the `next` branch.

**Comment by carlosmn** [comment] 2016-05-18 16:04
Likely because GitHub tries to avoid disclosing the existence of a repository by returning 401 for invalid credentials. We do test for not providing credentials, so I'm not sure what's happening there.

**Comment by AaronO** [comment] 2016-10-25 11:10
@carlosmn This seems like it's a duplicate of https://github.com/libgit2/git2go/issues/335

We should probably fix this, `git2go` should not panic/segfault which can't be recovered from but instead return an error.

@clns Check this code here for a workaround: https://gist.github.com/AaronO/4bea94ae93885d4a05af7cc417f72e1f#file-libgit2-clone-segfault-go-L20-L24

The segfault happens because you have no `CredentialsCallback` set, which `libgit2` uses whenever the http server doesn't reply with a `200` and asks for auth

To fix it, you can set your `CredentialsCallback` to `makeCredentialsCallback("", "")`, which is essentially providing no auth.

**Comment by AaronO** [comment] 2017-01-17 10:39
@carlosmn I think we can close this, since it's a duplicate of https://github.com/libgit2/git2go/issues/335 which was fixed by https://github.com/libgit2/git2go/pull/319

**Closed** 2017-01-17 14:21 UTC
